name: Deploy Serverless

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust according to your project
          cache: 'yarn'  # Cache dependencies for faster builds

      - name: Install Yarn
        run: yarn install  # Ensure Yarn is installed globally

      - name: Install Serverless Framework Locally
        run: yarn add serverless --dev  # Install Serverless as a dev dependency

      - name: Verify Serverless Installation
        run: npx serverless --version  # Ensure Serverless is installed

      - name: Install Dependencies
        run: yarn install --frozen-lockfile  # Install all project dependencies
     
      - name: Deploy with Serverless Framework
        run: npx serverless deploy  # Use npx to run Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}


        
              


