name: Deploy to aws

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn install

    - name: Show deployment ZIP file size
      run: |
          echo "Listing ZIP files in .serverless folder:"
          ls -lh .serverless/*.zip



    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Deploy to AWS with Serverless
      uses: serverless/github-action@v3.2  
      with:
       args: package
      env:
         SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

    - name: Show deployment ZIP file size
      run: |
          echo "Listing ZIP files in .serverless folder:"
          ls -lh .serverless/*.zip
      
